### ISSUE TITLE
Absolute joke from a security perspective

### ISSUE THREAD

**Issue by prabhu** [actions/hello-world-javascript-action#5]
This sample project recommends devs to upload the entire `node_modules` directory. While using such a simple plugin the entire codebase including `node_modules` is then downloaded and used without any sort of checks.

What is stopping people from uploading malicious stuff inside such node_modules to steal source code or inject exploits while using such actions?

**Comment by rzr** [comment]
Can't npm install be used at run time ?

**Comment by ncalteen** [comment]
Hi All, I submitted a PR to this repo to switch how this is currently handled. Instead of committing `node_modules` or including a `npm install` step before the action is run, this approach uses `@vercel/ncc` to package dependencies into a single JS file. This is the same approach used in the [TypeScript](https://github.com/actions/typescript-action) and [JavaScript](https://github.com/actions/javascript-action) action templates.
